param(
    [switch]$PrintCommandOnly,
    [string]$CodexExe = "C:\Users\37274\AppData\Roaming\npm\codex.cmd"
)

$ErrorActionPreference = "Stop"

$RepoRoot = "D:\Git_Repo\Paper-Analysis-New"
$RepoFullName = "MozhiJiawei/Paper-Analysis-Renew"
$TimeZone = [System.TimeZoneInfo]::FindSystemTimeZoneById("China Standard Time")
$NowShanghai = [System.TimeZoneInfo]::ConvertTime([DateTimeOffset]::UtcNow, $TimeZone)
$PaperDateLagDays = 4
$PaperDate = $NowShanghai.Date.AddDays(-$PaperDateLagDays)
$SubscriptionDate = $PaperDate.ToString("yyyy-MM/MM-dd")

$RunStamp = $NowShanghai.ToString("yyyyMMdd-HHmmss")
$LogRoot = Join-Path $RepoRoot "artifacts\automations\arxiv-github-issue-codex\$RunStamp"
New-Item -ItemType Directory -Force -Path $LogRoot | Out-Null

$env:PYTHONUTF8 = "1"
$env:PYTHONIOENCODING = "utf-8"

$Prompt = @(
    "Run the daily arXiv report workflow in repository D:\Git_Repo\Paper-Analysis-New, then publish the result to a GitHub Issue in repository $RepoFullName.",
    "",
    "Network access is explicitly allowed. Use the Gmail arXiv subscription email source, external web pages or APIs needed by the repository workflow, local GROBID if available, and GitHub. Do not force the arXiv API source. Do not call --deliver-subscription.",
    "",
    "The Windows scheduled script has computed the arXiv paper-content date in Asia/Shanghai as: $SubscriptionDate. Use this value as the CLI date argument.",
    "This is intentionally not the same as the email received date: arXiv subscription emails lag the paper Date fields. The current automation uses a $PaperDateLagDays-day lag from the Asia/Shanghai run date so that the requested paper date is present in the latest available subscription email.",
    "",
    "First run this stable repository CLI command:",
    "",
    "py -m paper_analysis.cli.main arxiv report --subscription-date $SubscriptionDate --fetch-all",
    "",
    "The CLI defaults to subscription-email when --subscription-date is provided. If this command exits non-zero, do not drift to --source-mode subscription-api. Inspect stdout/stderr and report the concrete Gmail, GROBID, embedding, or GitHub failure reason.",
    "The CLI may advance the workflow in batches. If it reports incomplete progress, rerun the exact same CLI command until the final gated report exists. Do not publish partial results.",
    "",
    "After the command finishes, only treat the final gated report as publishable. The final report paths are:",
    "- artifacts/e2e/arxiv/daily/$($SubscriptionDate.Split('/')[0])/$($SubscriptionDate.Split('/')[1])/final-summary.md",
    "- artifacts/e2e/arxiv/daily/$($SubscriptionDate.Split('/')[0])/$($SubscriptionDate.Split('/')[1])/final-summary.zh.md (generated by the translation script after final-result.json exists)",
    "- artifacts/e2e/arxiv/daily/$($SubscriptionDate.Split('/')[0])/$($SubscriptionDate.Split('/')[1])/final-result.json",
    "- artifacts/e2e/arxiv/daily/$($SubscriptionDate.Split('/')[0])/$($SubscriptionDate.Split('/')[1])/final-result.csv",
    "- artifacts/e2e/arxiv/daily/$($SubscriptionDate.Split('/')[0])/$($SubscriptionDate.Split('/')[1])/final-stdout.txt",
    "",
    "Do not publish artifacts/e2e/arxiv/latest or non-final daily summary files as the GitHub Issue result unless the final-* files exist for this subscription date. If final-summary.md or final-result.json is missing, do not create or update the report issue with partial results. Instead, report that the workflow is incomplete and tell the AI/operator to continue by rerunning the same CLI command.",
    "",
    "Before creating or updating the GitHub Issue, generate the Chinese-readable report by running the repository translation script:",
    "",
    "py scripts\translate_arxiv_final_report.py --subscription-date $SubscriptionDate",
    "",
    "This script reads final-result.json and writes final-summary.zh.md in the same daily directory. It calls OpenRouter with deepseek/deepseek-v4-flash by default. Do not manually translate the report in the executing agent, and do not compress abstracts into one-line summaries.",
    "Translation scope is intentionally limited to paper titles and abstracts. Red-team recommendation reasons and blue-team opinions are already Chinese in the final report and must be preserved as-is.",
    "The translated report structure must keep blue-team false positives visible: section 2 is the disputed red-team paper section generated by the script, combining blue-team borderline recommendations and blue-team false positives because blue-team may itself be wrong. Do not silently remove blue-team false positives from the GitHub Issue report.",
    "Use the generated final-summary.zh.md as the source for the GitHub Issue body or comment. If the translation script fails, report the concrete OpenRouter/JSON/validation failure reason and the next step.",
    "",
    "Create or update a GitHub Issue in $RepoFullName to carry this report. Use the GitHub issue creation capability available in the Codex session. If an open issue already exists for subscription date $SubscriptionDate, add a comment with the latest run result instead of creating a duplicate. Otherwise create a new issue.",
    "",
    "Issue title format: arXiv report $SubscriptionDate",
    "",
    "Issue body requirements:",
    "- Include subscription date, fetched paper count, recommended paper count, generation time, and local artifact paths.",
    "- Include the title/abstract bilingual Markdown summary derived from final-summary.zh.md, or a concise high-signal excerpt if GitHub body length would be too large.",
    "- Mention that email delivery is intentionally disabled and GitHub Issue is the delivery channel.",
    "- If report generation, bilingual translation, or GitHub issue creation fails, report the concrete failure reason and next step.",
    "",
    "Use the repository's existing stable CLI only. Do not create a new CLI namespace."
) -join [Environment]::NewLine

$PromptPath = Join-Path $LogRoot "prompt.txt"
$JsonLogPath = Join-Path $LogRoot "codex-events.jsonl"
$StderrLogPath = Join-Path $LogRoot "codex-stderr.txt"
$LastMessagePath = Join-Path $LogRoot "last-message.txt"
$ExitCodePath = Join-Path $LogRoot "exit-code.txt"

Set-Content -Path $PromptPath -Value $Prompt -Encoding UTF8

$Arguments = @(
    "--dangerously-bypass-approvals-and-sandbox",
    "--sandbox", "danger-full-access",
    "--search",
    "-c", "shell_environment_policy.inherit=all",
    "-C", $RepoRoot,
    "exec",
    "--json",
    "--output-last-message", $LastMessagePath,
    "-"
)

if ($PrintCommandOnly) {
    Write-Host "Codex executable: $CodexExe"
    Write-Host "Working directory: $RepoRoot"
    Write-Host "GitHub repository: $RepoFullName"
    Write-Host "Paper-content date: $SubscriptionDate"
    Write-Host "Paper date lag days: $PaperDateLagDays"
    Write-Host "Prompt path: $PromptPath"
    Write-Host "JSON log path: $JsonLogPath"
    Write-Host "Last message path: $LastMessagePath"
    Write-Host "Command:"
    Write-Host "`"$CodexExe`" $($Arguments -join ' ')"
    exit 0
}

Push-Location $RepoRoot
try {
    $Process = Start-Process `
        -FilePath $CodexExe `
        -ArgumentList $Arguments `
        -RedirectStandardInput $PromptPath `
        -RedirectStandardOutput $JsonLogPath `
        -RedirectStandardError $StderrLogPath `
        -NoNewWindow `
        -Wait `
        -PassThru
    $ExitCode = $Process.ExitCode

    if ($ExitCode -ne 0 -and (Test-Path $LastMessagePath)) {
        $LastMessage = Get-Content -Path $LastMessagePath -Raw -Encoding UTF8
        if ($LastMessage -match "github\.com/.+/issues/\d+" -or $LastMessage -match "Published the report to GitHub Issue") {
            $ExitCode = 0
        }
    }

    Set-Content -Path $ExitCodePath -Value $ExitCode -Encoding UTF8
    exit $ExitCode
}
finally {
    Pop-Location
}
